# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.2

# Mod Properties
mod_version=1.3.0
maven_group=nl.theepicblock
archives_base_name=proper-pet-tp

# Dependencies
fabric_version=0.149.0+26.1.2
